"""Stage 8c: exports for external tools and clinical reporting.

* legacy VTK unstructured grids (ParaView; same format Cardio-PINN writes),
* openCARP mesh (.pts/.elem/.lon) + stimulus vertices + parameter template,
* JSON digital-twin report (consumed by the Echocardiology dashboard bridge).
"""

from __future__ import annotations

import json
import os
from typing import Dict, Optional

import numpy as np


def write_vtk(path: str, points, tets, point_data: Optional[Dict[str, np.ndarray]] = None,
              cell_data: Optional[Dict[str, np.ndarray]] = None):
    points = np.asarray(points, float)
    tets = np.asarray(tets, int)
    with open(path, "w") as f:
        f.write("# vtk DataFile Version 4.0\nCardioSolv digital twin\nASCII\nDATASET UNSTRUCTURED_GRID\n")
        f.write(f"POINTS {len(points)} float\n")
        np.savetxt(f, points, fmt="%.6f")
        f.write(f"CELLS {len(tets)} {len(tets) * 5}\n")
        np.savetxt(f, np.c_[np.full(len(tets), 4), tets], fmt="%d")
        f.write(f"CELL_TYPES {len(tets)}\n")
        np.savetxt(f, np.full(len(tets), 10), fmt="%d")
        for header, data, n in (("POINT_DATA", point_data, len(points)), ("CELL_DATA", cell_data, len(tets))):
            if not data:
                continue
            f.write(f"{header} {n}\n")
            for name, arr in data.items():
                arr = np.asarray(arr, float)
                if arr.ndim == 2 and arr.shape[1] == 3:
                    f.write(f"VECTORS {name} float\n")
                    np.savetxt(f, arr, fmt="%.6g")
                else:
                    f.write(f"SCALARS {name} float 1\nLOOKUP_TABLE default\n")
                    np.savetxt(f, arr.reshape(-1), fmt="%.6g")
    return path


def export_vtk_series(folder, mesh, coords, ep, cycle, every=1):
    os.makedirs(folder, exist_ok=True)

    paths = []
    static = {"x_t": coords.x_t, "x_l": coords.x_l, "x_c": coords.x_c, "fiber": coords.fiber_nodes}
    if ep is not None:
        static["activation_time"] = ep.activation_time
        static["apd"] = ep.apd
    paths.append(write_vtk(os.path.join(folder, "anatomy.vtk"), mesh.points, mesh.tets, static,
                           {"fiber": coords.fiber, "sheet": coords.sheet}))
    if cycle is not None:
        for k in range(0, cycle.frame_count(), every):
            t = float(cycle.times[k])
            pd = {"displ": cycle.displacements[k]}
            if ep is not None:
                pd["vm"] = ep.vm(max(t, -1.0))
            cd = {"active_tension_kpa": cycle.active_tension_kpa[k]}
            for name, arr in cycle.element_fields.items():
                cd[name] = arr[k]
            paths.append(write_vtk(os.path.join(folder, f"Displ_{k:03d}.vtk"), mesh.points + cycle.displacements[k],
                                   mesh.tets, pd, cd))
    return paths


def export_opencarp(folder, mesh, coords, ep=None, name="cardiosolv"):
    """openCARP mesh in micrometres with fibres/sheets and the pacing sites."""
    os.makedirs(folder, exist_ok=True)
    base = os.path.join(folder, name)
    pts_um = mesh.points * 1000.0
    with open(base + ".pts", "w") as f:
        f.write(f"{len(pts_um)}\n")
        np.savetxt(f, pts_um, fmt="%.3f")
    tags = np.where(coords.x_t[mesh.tets].mean(1) < 0.33, 1, np.where(coords.x_t[mesh.tets].mean(1) < 0.66, 2, 3))
    with open(base + ".elem", "w") as f:
        f.write(f"{len(mesh.tets)}\n")
        for t, tag in zip(mesh.tets, tags):
            f.write(f"Tt {t[0]} {t[1]} {t[2]} {t[3]} {tag}\n")
    with open(base + ".lon", "w") as f:
        f.write("2\n")
        np.savetxt(f, np.c_[coords.fiber, coords.sheet], fmt="%.6f")
    files = [base + ".pts", base + ".elem", base + ".lon"]
    if ep is not None:
        with open(os.path.join(folder, "stimulus.vtx"), "w") as f:
            f.write(f"{len(ep.stim_nodes)}\nintra\n")
            np.savetxt(f, ep.stim_nodes, fmt="%d")
        files.append(os.path.join(folder, "stimulus.vtx"))
    par = os.path.join(folder, "cardiosolv.par")
    with open(par, "w") as f:
        f.write(f"""# openCARP parameter template generated by CardioSolv
meshname = {name}
simID = cardiosolv_ep
tend = 500
dt = 20
num_imp_regions = 1
imp_region[0].im = tenTusscherPanfilov
num_gregions = 1
gregion[0].num_IDs = 3
gregion[0].ID = 1 2 3
gregion[0].g_il = 0.174
gregion[0].g_it = 0.019
gregion[0].g_el = 0.625
gregion[0].g_et = 0.236
num_stim = 1
stim[0].crct.type = 0
stim[0].elec.vtx_file = stimulus
stim[0].pulse.strength = 250.0
stim[0].ptcl.duration = 2.0
stim[0].ptcl.start = 0
""")
    files.append(par)
    return files


def _jsonable(x):
    if isinstance(x, dict):
        return {str(k): _jsonable(v) for k, v in x.items()}
    if isinstance(x, (list, tuple)):
        return [_jsonable(v) for v in x]
    if isinstance(x, np.ndarray):
        return _jsonable(x.tolist())
    if isinstance(x, (np.floating, float)):
        return None if not np.isfinite(x) else float(x)
    if isinstance(x, (np.integer,)):
        return int(x)
    return x


def write_report(path, report: dict):
    with open(path, "w") as f:
        json.dump(_jsonable(report), f, indent=2)
    return path
